language: php

dist: trusty

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true

  global:
    - DEFAULT=1

  include:
    - php: 7.1
      env: PHPCS=1 DEFAULT=0

    - php: 7.1
      env: PHPSTAN=1 DEFAULT=0

before_script:
  - if [[ $DEFAULT = 1 ]]; then composer install; fi
  - if [[ $DEFAULT = 1 ]]; then composer require phpunit/phpunit:"^7.0"; fi
  - if [[ $DEFAULT = 1 ]]; then composer run-script post-install-cmd --no-interaction; fi
  - if [[ $PHPSTAN = 1 ]]; then composer require --dev "phpstan/phpstan"; fi

script:
  - if [[ $DEFAULT = 1 ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPCS = 1 ]]; then composer require "cakephp/cakephp-codesniffer^3.0"; composer cs-check; fi
  - if [[ $PHPSTAN = 1 ]]; then vendor/bin/phpstan analyse -l 5 src; fi

notifications:
  email: false
