language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - sh -c "composer global require 'cakephp/cakephp-codesniffer:*'"
  - phpenv rehash

script:
  - sh -c "~/.composer/vendor/bin/phpcs -p --extensions=php --standard=~/.composer/vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests ./webroot"

notifications:
  email: false
