language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - DEFAULT=1

matrix:
  include:
    - php: 7.3
      env: CHECKS=1 DEFAULT=0

    - php: 7.2
      env: PHPSTAN=1 DEFAULT=0

before_install:
  - phpenv config-rm xdebug.ini

before_script:
  - if [[ $DEFAULT == 1 || $PHPCS == 1 ]]; then composer install; fi
  - if [[ $DEFAULT == 1 ]]; then composer run-script post-install-cmd --no-interaction; fi
  - if [[ $PHPSTAN == 1 ]]; then composer require --dev phpstan/phpstan:^0.12; fi

script:
  - if [[ $DEFAULT == 1 ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPCS == 1 ]]; then composer cs-check; fi
  - if [[ $PHPSTAN == 1 ]]; then vendor/bin/phpstan analyse src/; fi

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false
